### ISSUE TITLE
Reset width

### ISSUE THREAD

**Issue by deasems** [Ayc0/mock-match-media#2]
I'm using this library in a jest-based project. I assume the effects of `setMedia` persist between tests. If that's the case could you consider 1. an api to reset all properties to default. and 2. call this new api automatically for test environments that have an afterEach hook? ([like how RTL does it with cleanup](https://testing-library.com/docs/react-testing-library/api#cleanup))

**Comment by Ayc0** [comment]
@deasems that's a good idea.

I'll see what I can do

**Comment by Ayc0** [comment]
@deasems I merged #10 that is doing this
It'll be released in the v0.2.0
