### ISSUE TITLE
A sincere thank you

### ISSUE THREAD

**Issue by emkis** [Ayc0/mock-match-media#36]
Hey @Ayc0 , I know this is not the best place to write this, but thank you for creating this library!

I've tested many different mocks and none was as straightforward as this one, and this solves all problems I'm having to unit test highly dynamic components in various screen sizes.

Again, thanks for all the effort you are putting into this library, you are awesome ❤️

**Comment by Ayc0** [comment]
This is really nice to hear! Thank you 🎉

**Comment by Ayc0** [comment]
@emkis FYI we are working on a stable v1, with support for CSS spec 5 for media query
